<?xml version="1.0"?>
<package format="3">
  <name>controleurs</name>
  <version>0.0.1</version>
  <description>Les controleurs du projet PROBO n° 11 de l'ecole Centrale</description>

  <maintainer email="hhamzi.in@gmail.com">Hamza</maintainer>
  <license>Apache-2.0</license>
  <author>Hamza Haytoumi</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>trajectory_msgs</depend>
  <depend>control_msgs</depend>
  <depend>std_msgs</depend>
  <exec_depend>python3-tk</exec_depend>
  <depend>kdl_parser</depend>
  <depend>orocos_kdl</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
